title: "Home"
description: "Copyright © 2025 Raffael Kaas. All rights reserved. Opinions are my"
# author:
#   name: Raffael Kaas
# url: "https://raffael-kaas7.github.io"
# baseurl: ""

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# header_pages:
#   - about.md
#   - interests.md
